enquete/enquete/urls.py
from django.conf import settings
#from django.conf.urls.static import static

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', include('home.urls')),
    path('review/', include('review.urls')),
    path('main/', include('main.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

enquete/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.indexView, name='home'),
]

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('enquete/<int:pk>',
        views.DetalhesView.as_view(), name='detalhes'
    ),
    path('enquete/<int:pk>/comentario',
        views.DetalhesComentarioView.as_view(), name='detalhes_comentario'
    ),
    path('enquete/<int:pk>/resultado',
        views.ResultadoView.as_view(), name='resultado'
    ),
    path('enquete/<int:id_enquete>/votacao',
        views.votacao, name='votacao'
    ),
]

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Pergunta(models.Model):
    texto = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora

class Opcao(models.Model):
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default = 0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto


class Comentario(models.Model):
    texto = models.CharField(max_length=280)
    nomeAutor = models.CharField(max_length = 120)
    data_publicacao = models.DateTimeField('Data de publicação')
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Pergunta, Opcao, Comentario

class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'ultimas_perguntas'
    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()).order_by(
            '-data_publicacao')[:5]

class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'main/detalhes.html'
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())

class DetalhesComentarioView(generic.DetailView):
    #model = Pergunta
    model = Comentario
    template_name = 'main/detalhes_comentario.html'
    def get_queryset(self):
        return Comentario.objects.filter(data_publicacao__lte=timezone.now())



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'

def votacao(request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk=id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'main/detalhes.html', {
            'pergunta': pergunta,
            'error_message': "Selecione uma opção Válida!"
        })
    else:
        opcao_selecionada.votos +=1
        opcao_selecionada.save()
        return HttpResponseRedirect(
            reverse('main:resultado', args=(pergunta.id,))
        )

def detalhesComentario(request, id_comentario):

    pergunta = get_object_or_404(Pergunta, pk=id_comentario)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'main/detalhes.html', {
            'pergunta': pergunta,
            'error_message': "Selecione uma opção Válida!"
        })
    else:
        return HttpResponseRedirect(
            reverse('main:detalhes', args=(pergunta.id,))
        )

enquete/main/templates/main/detalhes.html
<html>
    <head></head>
    <body>

        <h1>Detalhes da Enquete {{ pergunta.id }}</h1>
        <u>Pergunta</u>: {{ pergunta.texto }} <br>
        <u>Data da Publicação</u>: {{ pergunta.data_publicacao }}
        {% if error_message %}
            <hr/>
                <strong>{{ error_message }}</strong>
            <hr/>
        {% endif%}
        <form action="{% url 'main:votacao' pergunta.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                    <li><input type="radio" name="opcao"
                    id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
                        <label for="opcao{{ forloop.counter }}">
                            {{ opcao.texto }}
                        </label>
                    </li>
                {% endfor %}

            </ul>
            <input type="submit" value="Registre o Seu Voto">
        </form>
        <h2>Comentários</h2>
        <ul>
            {% for comentario in pergunta.comentario_set.all %}
                <li>
                    <label for="comentario{{ forloop.counter }}">
                        <a href="{% url 'main:detalhes_comentario' comentario.id %}">{{ comentario.texto }}</a>
                    </label>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'main:index' %}">Ir à Página Principal</a>




    </body>

</html>

enquete/main/templates/main/detalhes_comentario.html
<html>
    <head></head>
    <body>
        Detalhes Comentarios
        <h2>Comentários</h2>

        <ul>
            <li>{{ comentario.nomeAutor }}</li>
            <li>{{ comentario.texto }}</li>
            <li>{{ comentario.data_publicacao }}</li>

        </ul>
        <a href="{% url 'main:detalhes' comentario.pergunta_id %}">Voltar A Enquete?</a>
        <a href="{% url 'main:index' %}">Ir à Página Principal</a>
    </body>

</html>

enquete/main/templates/main/index.html
<html>
    <head>
        <title>App Enquete</title>
    </head>
    <body>
        {% if ultimas_perguntas %}
            <h2>Lista das últimas enquetes</h2>
            <ul>
                {% for pergunta in ultimas_perguntas %}
                    <li><a href="{% url 'main:detalhes' pergunta.id %}">
                        {{pergunta.texto}}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Não há Enquetes Cadastradas até o Momento</p>
        {% endif %}
    </body>
</html>

enquete/main/templates/main/resultado.html
<html>
    <head>
        <title>App enquete</title>
    </head>
    <body>
        <h2>Resultado Parcial da Enquete {{ pergunta.id }}</h2>
        <u>Pergunta</u>: {{ pergunta.texto }}<br/>
        <u>Data da Publicação</u>: {{ pergunta.data_publicacao }}
        <ul>
            {% for opcao in pergunta.opcao_set.all %}
                <li>{{ opcao.texto }} = {{ opcao.votos }}
                voto{{ opcao.votos | pluralize }} </li>
            {% endfor %}
        </ul>
        <hr/>
        <a href="{% url 'main:detalhes' pergunta.id %}">Votar Novamente?</a>
        <a href="{% url 'main:index' %}">Ir à Página Principal</a>
    </body>
</html>