enquete/enquete/urls.py
from django.conf import settings
#from django.conf.urls.static import static

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', include('home.urls')),
    path('review/', include('review.urls')),
    path('main/', include('main.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

enquete/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.indexView, name='home'),
]

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('enquete/<int:pk>',
        views.DetalhesView.as_view(), name='detalhes'
    ),
    path('enquete/<int:pk>/comentario',
        views.DetalhesComentarioView.as_view(), name='detalhes_comentario'
    ),
    path('enquete/<int:pk>/resultado',
        views.ResultadoView.as_view(), name='resultado'
    ),
    path('enquete/<int:id_enquete>/votacao',
        views.votacao, name='votacao'
    ),
]

enquete/review/urls.py
from django.urls import path
from . import views
from django.contrib.auth import logout
from django.conf.urls import url

from django.contrib.auth.views import LogoutView

app_name = 'review'
urlpatterns = [
    path('review/', views.IndexView.as_view(), name='reviews'),
    #path('<int:pk>', views.IndexView.as_view(), name='index'),
    path('review/<int:pk>',
        views.DetalhesView.as_view(), name='detalhes'
    ),
    path('review/<int:pk>/comentario',
        views.DetalhesComentarioView.as_view(), name='detalhes_comentario'
    ),
    path('review/<int:pk>/resultado',
        views.ResultadoView.as_view(), name='resultado'
    ),
    path('review/<int:id_post>/votacao',
        views.votacao, name='votacao'
    ),

    path('review/<int:pk>/criar_post',
        views.CriarPostView.as_view(), name='criar_post'
    ),
    path('review/<int:id_user>/form_post',
        views.formPost, name='form_post'
    ),


    path('review/cadastro',
        views.iniciarCadastro, name='cadastro'
    ),
    path('review/acessarsistema',
        views.acessarSistema, name='acessarsistema'
    ),
    path('review/formcadastro',
        views.acessarCadastro, name='formcadastro'
    ),

    #url(r'^sign-out/$', logout, {'template_name': 'index.html', 'next_page': '/'}, name='sign-out'),
    #url(r'^logout$', LogoutView.as_view(),  name='logout'),


    path('review/logout',
        views.logout, name='logout'
    ),


    path('review/dashboard',
        views.acessarDashboard , name='dashboard'
    ),

    path('review/login',
        views.login, name='irtelalogin'
    ),
    path('review/realizarlogin',
        views.realizarLogin, name='realizarlogin'
    ),

    path('review/<int:id_game>/game',
        views.openGame, name='opengame'
    ),

]

enquete/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Iury Macks">
    <meta name="keywords"content = "Arte, Review, Tecnologia"/>
    <meta name="ROBOTS" content ="Index,follow"/>
    <title> Review</title>
    <!-- estilo CSS
    <link rel="stylesheet" type="text/css"  href="{% static '' %}" />  -->
    <link rel="apple-touch-icon-precomposed" href="{% static 'assets/img/apple-touch-icon.png' %}" />
    <link rel="stylesheet" type="text/css"  href="{% static 'assets/css/uikit.min.css' %}" />
    <link rel="stylesheet" type="text/css"  href="{% static 'assets/css/theme.css' %}" />

    <link rel="stylesheet" type="text/css"  href="{% static 'css/detalhes.css' %}" />


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" >
</head>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#dual-collapse2" aria-controls="dual-collapse2" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  <a class="mx-auto" href="{% url 'home:home' %}">
    <img class=" w-20" src="/media/imgs/logoblack2.png">
  </a>

  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="dual-collapse2">
    <ul class="navbar-nav ml-auto" style="font-size: large;">

          <li class="nav-item active">
              <a class="nav-link mr-sm-2" style="color: white;" href="{% url 'review:reviews' %}">Inicio</a>
          </li>

      {% if request.user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link mr-sm-2" style="color: white;" href="{% url 'review:dashboard' %}">Posts</a>
            </li>

      {% endif %}
      {% if request.user.is_authenticated %}

          <li class="nav-item">
              <a class="nav-link mr-sm-2" style="color: white;" href="{% url 'review:logout' %}">Sair</a>
          </li>


        <li class="nav-item">
          <a class="nav-link" href="#">{{request.user.username}}</a>
        </li>


        <li class="nav-item">
          <img src="{{request.user.photo.url}}" class="rounded-circle mr-sm-2" alt="Cinque Terre" width="42" height="42">
        </li>

      {% else %}

            <li class="nav-item">
                <a class="nav-link mr-sm-2" href="{% url 'review:irtelalogin' %}">Entrar</a>
            </li>

      {% endif %}
    </ul>
  </div>
</nav>
<img class="img-responsive" src="/media/imgs/darkArt.jpg" alt="Chania"  >

<div class="d-flex justify-content-around" style="background-color: white;">
  <!--<img class="img-responsive" src="/media/imgs/eyeMonster.gif" alt="Chania"> -->
</div>

<body >
  {% block content %}

  {% endblock %}

</body>


<footer class="mastfoot mt-auto" style="text-align: center; background-color: black;">
  <div class="inner">
    <p style="color: aliceblue;">Copyright © 2015-2020 <a href="https://www.instagram.com/nablasoftwares/">NablaSoftwares</a>. Todos os direitos reservados.</p>
  </div>
  <div class="navbar-collapse collapse w-100 dual-collapse2 order-2 order-md-2">
    <ul class="navbar-nav mr-auto text-center">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'main:index' %}">Site Enquete</a>
        </li>
    </ul>
</div>
</footer>

</html>

enquete/templates/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

{{message}}

<main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Escolha Uma Aplicação</h1>
        <p>
          <a href="{% url 'review:reviews' %}" class="btn btn-primary my-2">Aplicação Review</a>
          <a href="{% url 'main:index' %}" class="btn btn-secondary my-2">Aplicação Enquete</a>
        </p>
      </div>
    </section>

  </main>

{% endblock %}