enquete/enquete/urls.py
from django.conf import settings
#from django.conf.urls.static import static

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', include('home.urls')),
    path('review/', include('review.urls')),
    path('main/', include('main.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

enquete/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.indexView, name='home'),
]

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('enquete/<int:pk>',
        views.DetalhesView.as_view(), name='detalhes'
    ),
    path('enquete/<int:pk>/comentario',
        views.DetalhesComentarioView.as_view(), name='detalhes_comentario'
    ),
    path('enquete/<int:pk>/resultado',
        views.ResultadoView.as_view(), name='resultado'
    ),
    path('enquete/<int:id_enquete>/votacao',
        views.votacao, name='votacao'
    ),
]

enquete/review/urls.py
from django.urls import path
from . import views
from django.contrib.auth import logout
from django.conf.urls import url

from django.contrib.auth.views import LogoutView

app_name = 'review'
urlpatterns = [
    path('review/', views.IndexView.as_view(), name='reviews'),
    #path('<int:pk>', views.IndexView.as_view(), name='index'),
    path('review/<int:pk>',
        views.DetalhesView.as_view(), name='detalhes'
    ),
    path('review/<int:pk>/comentario',
        views.DetalhesComentarioView.as_view(), name='detalhes_comentario'
    ),
    path('review/<int:pk>/resultado',
        views.ResultadoView.as_view(), name='resultado'
    ),
    path('review/<int:id_post>/votacao',
        views.votacao, name='votacao'
    ),

    path('review/<int:pk>/criar_post',
        views.CriarPostView.as_view(), name='criar_post'
    ),
    path('review/<int:id_user>/form_post',
        views.formPost, name='form_post'
    ),


    path('review/cadastro',
        views.iniciarCadastro, name='cadastro'
    ),
    path('review/acessarsistema',
        views.acessarSistema, name='acessarsistema'
    ),
    path('review/formcadastro',
        views.acessarCadastro, name='formcadastro'
    ),

    #url(r'^sign-out/$', logout, {'template_name': 'index.html', 'next_page': '/'}, name='sign-out'),
    #url(r'^logout$', LogoutView.as_view(),  name='logout'),


    path('review/logout',
        views.logout, name='logout'
    ),


    path('review/dashboard',
        views.acessarDashboard , name='dashboard'
    ),

    path('review/login',
        views.login, name='irtelalogin'
    ),
    path('review/realizarlogin',
        views.realizarLogin, name='realizarlogin'
    ),

    path('review/<int:id_game>/game',
        views.openGame, name='opengame'
    ),

]

enquete/home/models.py
from django.db import models

# Create your models here.

enquete/review/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
import datetime

# Create your models here.
class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, cpf, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')
		

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, cpf, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
			cpf=cpf,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user

class Account(AbstractBaseUser):
	email = models.EmailField(verbose_name="email", max_length=60, unique=True)
	username = models.CharField(max_length=30, unique=True)
	cpf = models.CharField(max_length=30)
	date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	is_staff = models.BooleanField(default=False)
	is_superuser = models.BooleanField(default=False)
	photo = models.ImageField(upload_to='users')

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return self.email

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True


class Post(models.Model):
	titulo = models.CharField(max_length=128)
	descricao = models.CharField(max_length=200)
	data_publicacao = models.DateTimeField('Data de publicação')
	total_votos = models.IntegerField(default=0)
	user = models.ForeignKey(Account, on_delete=models.CASCADE)
	mediaEstrelas = models.DecimalField(default=0, max_digits=3, decimal_places=2)
	def __str__(self):
		return self.titulo
	def publicada_recentemente(self):
		agora = timezone.now()
		return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora

class Comentario(models.Model):
    texto = models.CharField(max_length=280)
    nomeAutor = models.CharField(max_length = 120)
    data_publicacao = models.DateTimeField('Data de publicação')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postComentario')
    def __str__(self):
        return self.texto

class Fotos(models.Model):
    titulo = models.CharField(max_length=128)
    data_publicacao = models.DateTimeField('Data de publicação')
    image = models.ImageField(upload_to='image_review')
    nota = models.IntegerField(default = 0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postImagens')
    def __str__(self):
        return self.titulo

class Estrelas(models.Model):
    estrelas = models.IntegerField(default = 0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postEstrelas')
    def __str__(self):
        return str(self.estrelas)

enquete/home/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
def indexView(request):
    return render(request, 'index.html', {
        'post': 'post',
    })

enquete/review/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Account, Post, Fotos, Comentario, Estrelas
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as django_logout

from django.contrib.auth.views import LogoutView

class IndexView(generic.ListView):
    template_name = 'review/home.html'
    context_object_name = 'all_posts'
    def get_queryset(self):
        queryset = {
            'allposts': Post.objects.filter(data_publicacao__lte=timezone.now()).order_by(
            '-data_publicacao'),
            'nomePainel': 'Ir Para O Painel',
            'nomeCadastrese': 'Cadastre-se',
        }
        return queryset


def formPost(request, id_user):
    return render (request, 'user/create_post.html', {"userId": id_user })


class CriarPostView(generic.ListView):
    model = Post
    template_name = 'review/dashboard.html'
    context_object_name = 'usuarioCriarPost'


    def post(self, request, *args, **kwargs):
        usuario = Account.objects.get(pk=request.user.id)
        postagem = Post.objects.create(user=usuario,
        titulo = request.POST['titulo'],
        descricao=request.POST['descricao'],
        data_publicacao=timezone.now(),
        )

        img1 = None
        img2 = None
        img3 = None

        if request.FILES['photo'] is not None:
            img1 = request.FILES['photo']
        if request.FILES['photo2'] is not None:
            img2 = request.FILES['photo2']
        if request.FILES['photo3'] is not None:
            img3 = request.FILES['photo3']

        if img1 is not None:
            foto = Fotos(titulo=postagem.titulo + '-1',data_publicacao=timezone.now(), image=img1, post=postagem)
            foto.save()
        if img2 is not None:
            foto2 = Fotos(titulo=postagem.titulo + '-2',data_publicacao=timezone.now(), image=img2, post=postagem)
            foto2.save()
        if img3 is not None:
            foto3 = Fotos(titulo=postagem.titulo + '-3',data_publicacao=timezone.now(), image=img3, post=postagem)
            foto3.save()

        #post.postImagens.add(foto)
        #post.postImagens.add(foto2)
        postagem.mediaEstrelas = 1


        try:
            postagem.save()
        except (KeyError, Post.DoesNotExist):
            return render(request, 'review/dashboard.html', {
                'custom': usuario,
                'error_message': "Houve um erro ao tentar criar o post!"
            })
        else:
            return HttpResponseRedirect(
                reverse('review:detalhes', args=(postagem.id,))
            )

    def get_queryset(self):
        postObj = Post.objects.get(id=self.kwargs['pk'])
        estrelasRelated = postObj.postEstrelas.all()
        somaEstremas = 0
        for estrelas in estrelasRelated:
            somaEstremas += estrelas.estrelas
        if estrelasRelated.count() == 0:
            mediaEstrelas = 1
        else:
            mediaEstrelas = somaEstremas/estrelasRelated.count()
        #vari = Post.objects.get(id=self.kwargs['pk'])
        postObj.mediaEstrelas = round(mediaEstrelas)
        postObj.save()
        queryset = {'post': postObj,
        'media_estrelas': mediaEstrelas,
        'n' : range(5),
        'qntVotos': estrelasRelated.count(),
        'comentsRelated': postObj.postComentario.all().order_by('-data_publicacao')
        }
        return queryset


class DetalhesView(generic.ListView):
    model = Post
    template_name = 'review/detalhes.html'
    context_object_name = 'postDetalhes'


    def post(self, request, *args, **kwargs):
        post = Post.objects.get(id=self.kwargs['pk'])
        if request.method == 'POST':
            comentario = request.POST['comentario']

        try:
            novo_comentario = Comentario(texto = comentario, nomeAutor = 'Anonimo',
            data_publicacao=timezone.now(), post=post)
        except (KeyError, Comentario.DoesNotExist):
            return render(request, 'review/detalhes.html', {
                'post': post,
                'error_message': "Comentário Inválido!"
            })
        else:
            if novo_comentario is not None:
                novo_comentario.save()

            return HttpResponseRedirect(
                reverse('review:detalhes', args=(post.id,))
            )

    def get_queryset(self):
        postObj = Post.objects.get(id=self.kwargs['pk'])
        estrelasRelated = postObj.postEstrelas.all()
        somaEstremas = 0
        for estrelas in estrelasRelated:
            somaEstremas += estrelas.estrelas
        if estrelasRelated.count() == 0:
            mediaEstrelas = 1
        else:
            mediaEstrelas = somaEstremas/estrelasRelated.count()
        #vari = Post.objects.get(id=self.kwargs['pk'])
        postObj.mediaEstrelas = round(mediaEstrelas)
        postObj.save()
        queryset = {'post': postObj,
        'media_estrelas': mediaEstrelas,
        'n' : range(5),
        'qntVotos': estrelasRelated.count(),
        'comentsRelated': postObj.postComentario.all().order_by('-data_publicacao')
        }
        return queryset

class DetalhesComentarioView(generic.DetailView):
    model = Comentario
    template_name = 'review/detalhes_comentario.html'
    def get_queryset(self):
        return Comentario.objects.filter(data_publicacao__lte=timezone.now())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class ResultadoView(generic.DetailView):
    model = Post
    template_name = 'review/resultado.html'

def votacao(request, id_post):
    post = get_object_or_404(Post, pk=id_post)
    try:
        opcao_estrelas = Estrelas(estrelas=request.POST['estrelas'], post=post)
    except (KeyError, Estrelas.DoesNotExist):
        return render(request, 'review/detalhes.html', {
            'post': post,
            'error_message': "Selecione uma opção Válida!"
        })
    else:
        if opcao_estrelas is not None:
            opcao_estrelas.save()

        return HttpResponseRedirect(
            reverse('review:detalhes', args=(post.id,))
        )

def detalhesComentario(request, id_comentario):

    post = get_object_or_404(Post, pk=id_comentario)
    try:
        opcao_selecionada = post.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'review/detalhes.html', {
            'post': post,
            'error_message': "Selecione uma opção Válida!"
        })
    else:
        return HttpResponseRedirect(
            reverse('review:detalhes', args=(post.id,))
        )





def openGame(request, id_game):
    return render (request, 'games/darkEngineer/index.html')


def acessarSistema(request):
    return render (request, 'user/login.html')

def acessarCadastro(request):
    return render (request, 'user/signup.html')

def acessarDashboard(request):
    custom = Account.objects.get(username=request.user.username)
    return render (request, 'user/dashboard.html', {"custom": custom })

def logout(request):
    django_logout(request)
    return redirect("review:irtelalogin")

def login(request):
    return render(request, 'user/login.html')

def realizarLogin(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'],password=request.POST['password'])

        if user is not None:
            custom = Account.objects.get(username = user.username)
            auth_login(request, user)
            return render (request, "user/dashboard.html", {"custom": custom })
            #return redirect('homepage')
        else:
            return render(request,'user/login.html',{'error':'Usuario ou Senha esta incorreto!'})
    else:
        return render(request,'user/login.html')


def iniciarCadastro(request):
    username = request.POST['username']
    password = request.POST['password']
    email = request.POST['email']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']

    user = Account.objects.create(
    username = request.POST['username'],
    email = request.POST['email'],
    cpf = '',
    )
    user.set_password(request.POST['password'])
    #user.photo = request.POST['photo']

    if request.FILES['photo']:
        user.photo = request.FILES['photo']

    user.last_name = last_name
    user.first_name = first_name
    user.save()

    return render(request, "user/dashboard.html", {'custom': user , 'message': "Usuário criado com sucesso!"})

enquete/templates/review/detalhes.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}




{% block content %}
{{message}}

<div style="text-align: center;">
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
  <main role="main" class="inner cover">
    <h4 class="cover-heading">{{postDetalhes.post.titulo}}</h4>
  </main>
</div>

</div>





<div class="album py-5" style="background-color: black;">
  <div class="container" style="text-align: center;">


            <div id="carouselExampleIndicators" class="carousel slide md-6" data-ride="carousel">
              <ol class="carousel-indicators">
                {% for img in postDetalhes.post.postImagens.all %}
                  <li data-target="#carouselExampleIndicators{{forloop.counter}}" 
                  data-slide-to="{{forloop.counter}}" class="{% if forloop.counter == 1 %}active{% endif %}"></li>
                  
                {% endfor %}
              </ol>
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block mx-auto w-50  rounded" src="{{ postDetalhes.post.postImagens.first.image.url }}" alt="First slide">
                </div>
                {% for img in postDetalhes.post.postImagens.all %}
                  {% if img == postDetalhes.post.postImagens.first %}
                  
                  {% else %}
                  <div class="carousel-item">
                    <img class="d-block mx-auto w-50 rounded" src="{{ img.image.url }}" alt="First slide">
                  </div>
                  {% endif %}

                {% endfor %}
              </div>
              <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
            
            <div class="card-body" style="border-bottom: -30em;" >

              <h5 class="card-title" style="color:white;" >{{postDetalhes.post.titulo}}</h5>
              <h6 class="card-subtitle mb-2 text-muted" style="color:whitesmoke;">Desenvolvedor: {{postDetalhes.post.user.username}}</h6>
              <p class="card-text" style="color:white;">{{postDetalhes.post.descricao}}</p>

              <form action="{% url 'review:votacao' postDetalhes.post.id %}" method="POST">
                {% csrf_token %}
                <!-- Material inline 1 -->
                <div class="form-check form-check-inline">
                  <input type="radio" class="form-check-input" 
                  id="materialInline1-{{postDetalhes.post.id}}" name="estrelas" value="1">
                  <label class="form-check-label" for="materialInline1" style="color: white;">1</label>
                </div>

                <!-- Material inline 2 -->
                <div class="form-check form-check-inline">
                  <input type="radio" class="form-check-input" 
                  id="materialInline2-{{postDetalhes.post.id}}" name="estrelas" value="2">
                  <label class="form-check-label" for="materialInline2" style="color: white;">2</label>
                </div>

                <!-- Material inline 3 -->
                <div class="form-check form-check-inline">
                  <input type="radio" class="form-check-input" 
                  id="materialInline3-{{postDetalhes.post.id}}" name="estrelas" value="3">
                  <label class="form-check-label" for="materialInline3" style="color: white;">3</label>
                </div>

                <!-- Material inline 3 -->
                <div class="form-check form-check-inline">
                  <input type="radio" class="form-check-input" 
                  id="materialInline4-{{postDetalhes.post.id}}" name="estrelas" value="4">
                  <label class="form-check-label" for="materialInline4" style="color: white;">4</label>
                </div>

                <!-- Material inline 3 -->
                <div class="form-check form-check-inline">
                  <input type="radio" class="form-check-input" 
                  id="materialInline5-{{postDetalhes.post.id}}" name="estrelas" value="5">
                  <label class="form-check-label" for="materialInline5" style="color: white;">5</label>
                </div>
                <p >
                  <button type="submit" class="btn btn-dark btn-block"> Votar  </button>
                </p>
              </form>
            </div>

    <p style="color: aliceblue;">      
{{postDetalhes.qntVotos}} Votos 

</p>  
            <div class=" align-items-center" style="border-bottom: 8em;" >
              <div class="align-items-center" style="border-bottom: 8em;">
                <span class="rating">
                  {% for i in postDetalhes.n %}
                    {% if i < postDetalhes.media_estrelas %}
                      <i class="uk-icon-star" style="color: rgb(226, 226, 3);"></i>
                    {% else %}
                      <i class="uk-icon-star"></i>
                    {% endif %}
                  {% endfor %}
                </span>
              </div>                           
            </div>
          <br><br>
       
</div>


<!-- COMENTARIOS -->
<div class="container col-md-8">
  <div class="be-comment-block">
    <h1 class="comments-title" style="color: aliceblue;">Comentários</h1>


    <form class="form-block" action="{% url 'review:detalhes' postDetalhes.post.id %}" method="POST">
      {% csrf_token %}
      <div class="col-xs-12">									
        <div class="form-group">
          <textarea class="form-input" name="comentario" required="" id="comentario"
          placeholder="manda aí seu review ;D"></textarea>
        </div>
      </div>
      <div class="col-xs-4">
        <p >
          <button type="submit" class="btn btn-primary btn-block"> Enviar  </button>
        </p>
      </div>
    </form>


    {% for coment in postDetalhes.comentsRelated %}
    <div class="be-comment">
      <div class="be-img-comment">	
        <a href="#">
          <img src="/media/imgs/icon_anonymous.png" alt="" class="be-ava-comment">
        </a>
      </div>
      <div class="be-comment-content">
        
          <span class="be-comment-name">
            <a href="#" style="color: aliceblue;">Anônimo</a>
            </span>
          <span class="be-comment-time">
            <i class="fa fa-clock-o"></i>
            {{coment.data_publicacao}}
          </span>
  
        <p class="be-comment-text" style="color:black; font-size: large;">
          {{coment.texto}}
        </p>
      </div>
    </div>
    {% endfor %}
    
  </div>
  </div>

  <!-- FIM COMENTARIOS -->




{% endblock %}

enquete/templates/review/detalhes_comentario.html

    <ul class="nav fixed-top justify-content-end menu" >
      <li class="nav-item inicio">
        <a class="nav-link" href="{% url 'main:index' %}">Início</a>
      </li>
      <li class="nav-item sobre">
        <a class="nav-link" href="#">Sobre nós</a>
      </li>
      <li class="nav-item contato">
        <a class="nav-link " href="#">Contato</a>
      </li>
      <li class="nav-item login">
        
      </li>
    </ul>

enquete/templates/review/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

{{message}}
<main role="main" style="background-color: black;">

    <section class="jumbotron text-center"
        style="background-color: black;  margin-bottom: 7em; ">
      <div class="container" style="height:1.0em; background-color: black;">
        <h3 class="jumbotron-heading">Votaí</h3>
        <p class=" text-muted">Avalie e Seja Avaliado Por uma comunidade de Usuários e Designers!</p>
        {% if request.user.is_authenticated %}
          <p>
            <a href="{% url 'review:dashboard' %}" class="btn btn-primary my-2">{{all_posts.nomePainel}}</a>
          </p>
        {% else %}
          <p>
            <a href="{% url 'review:formcadastro' %}" class="btn btn-primary my-2">{{all_posts.nomeCadastrese}}</a>
          </p>
        {% endif %}
        <!-- BOTAO EXTERNO PARA MEU GAME HTML5 DARK ENGINEER -->
        <p style="margin-top: -1em;">
          <a href="https://thwir.000webhostapp.com/games/alone_1.85b/index.html"
          class="btn btn-secondary my-2" >Conheça Dark Engineer</a>
        </p>
      </div>
    </section>

    <div class="album py-5" style="background-color: black;">
      <div class="container">

        <div class="row">
          {% for post in all_posts.allposts %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">

                <div id="carouselExampleIndicators{{forloop.counter}}" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    {% for img in post.postImagens.all %}
                      <li data-target="#carouselExampleIndicators{{forloop.counter}}"
                      data-slide-to="{{forloop.counter}}" class="{% if forloop.counter == 1 %}active{% endif %}"></li>

                    {% endfor %}
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img class="d-block w-100" src="{{ post.postImagens.first.image.url }}" alt="First slide">
                    </div>
                    {% for img in post.postImagens.all %}
                      {% if img == post.postImagens.first %}

                      {% else %}
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{{ img.image.url }}" alt="First slide">
                      </div>
                      {% endif %}

                    {% endfor %}
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators{{forloop.counter}}" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators{{forloop.counter}}" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>




                <div class="card-body">

                  <h5 class="card-title" style="color:black;" >{{post.titulo}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Desenvolvedor: {{post.user.username}}</h6>
                  <p class="card-text">{{post.descricao}}</p>

                  <div class="d-flex justify-content-between align-items-center">
                      <div class="d-flex justify-content-between align-items-center">
                        <span class="rating">
                          {% for i in 'cinco' %}
                            {% if forloop.counter <= post.mediaEstrelas %}
                              <i class="uk-icon-star" style="color: rgb(226, 226, 3);"></i>
                            {% else %}
                              <i class="uk-icon-star"></i>
                            {% endif %}
                          {% endfor %}
                        </span>
                      </div>

                      <p>
                        <a href="{% url 'review:detalhes' post.id %}" class="btn btn-primary my-2">Detalhes</a>
                      </p>

                  </div>
                </div>
              </div>
            </div>
          {% endfor %}



      </div>
    </div>

</main>
{% endblock %}