enquete/enquete/urls.py
from django.conf import settings
#from django.conf.urls.static import static

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', include('home.urls')),
    path('review/', include('review.urls')),
    path('main/', include('main.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

enquete/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.indexView, name='home'),
]

enquete/review/urls.py
from django.urls import path
from . import views
from django.contrib.auth import logout
from django.conf.urls import url

from django.contrib.auth.views import LogoutView

app_name = 'review'
urlpatterns = [
    path('review/', views.IndexView.as_view(), name='reviews'),
    #path('<int:pk>', views.IndexView.as_view(), name='index'),
    path('review/<int:pk>',
        views.DetalhesView.as_view(), name='detalhes'
    ),
    path('review/<int:pk>/comentario',
        views.DetalhesComentarioView.as_view(), name='detalhes_comentario'
    ),
    path('review/<int:pk>/resultado',
        views.ResultadoView.as_view(), name='resultado'
    ),
    path('review/<int:id_post>/votacao',
        views.votacao, name='votacao'
    ),

    path('review/<int:pk>/criar_post',
        views.CriarPostView.as_view(), name='criar_post'
    ),
    path('review/<int:id_user>/form_post',
        views.formPost, name='form_post'
    ),


    path('review/cadastro',
        views.iniciarCadastro, name='cadastro'
    ),
    path('review/acessarsistema',
        views.acessarSistema, name='acessarsistema'
    ),
    path('review/formcadastro',
        views.acessarCadastro, name='formcadastro'
    ),

    #url(r'^sign-out/$', logout, {'template_name': 'index.html', 'next_page': '/'}, name='sign-out'),
    #url(r'^logout$', LogoutView.as_view(),  name='logout'),


    path('review/logout',
        views.logout, name='logout'
    ),


    path('review/dashboard',
        views.acessarDashboard , name='dashboard'
    ),

    path('review/login',
        views.login, name='irtelalogin'
    ),
    path('review/realizarlogin',
        views.realizarLogin, name='realizarlogin'
    ),

    path('review/<int:id_game>/game',
        views.openGame, name='opengame'
    ),

]

enquete/review/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
import datetime

# Create your models here.
class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, cpf, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')
		

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, cpf, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
			cpf=cpf,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user

class Account(AbstractBaseUser):
	email = models.EmailField(verbose_name="email", max_length=60, unique=True)
	username = models.CharField(max_length=30, unique=True)
	cpf = models.CharField(max_length=30)
	date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	is_staff = models.BooleanField(default=False)
	is_superuser = models.BooleanField(default=False)
	photo = models.ImageField(upload_to='users')

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return self.email

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True


class Post(models.Model):
	titulo = models.CharField(max_length=128)
	descricao = models.CharField(max_length=200)
	data_publicacao = models.DateTimeField('Data de publicação')
	total_votos = models.IntegerField(default=0)
	user = models.ForeignKey(Account, on_delete=models.CASCADE)
	mediaEstrelas = models.DecimalField(default=0, max_digits=3, decimal_places=2)
	def __str__(self):
		return self.titulo
	def publicada_recentemente(self):
		agora = timezone.now()
		return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora

class Comentario(models.Model):
    texto = models.CharField(max_length=280)
    nomeAutor = models.CharField(max_length = 120)
    data_publicacao = models.DateTimeField('Data de publicação')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postComentario')
    def __str__(self):
        return self.texto

class Fotos(models.Model):
    titulo = models.CharField(max_length=128)
    data_publicacao = models.DateTimeField('Data de publicação')
    image = models.ImageField(upload_to='image_review')
    nota = models.IntegerField(default = 0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postImagens')
    def __str__(self):
        return self.titulo

class Estrelas(models.Model):
    estrelas = models.IntegerField(default = 0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postEstrelas')
    def __str__(self):
        return str(self.estrelas)

enquete/templates/user/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container w-50" align="center" >
    User Id: {{userId}}
    <form action="{% url 'review:criar_post' userId %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>Título </label>
              <input type="text" name="titulo" id="titulo" class="form-control" placeholder="" required>
        </div> <!-- form-group end.// -->
        <div class="form-group">
            <label>Conte um Pouco Sobre o Game</label>
            <input type="textarea" name="descricao" id="descricao" required=''
            class="form-control" placeholder="">
        </div> <!-- form-group end.// -->

        <div class="form-group">
            <label for="photo">Imagem Inicial</label>
            <input type="file" name="photo" class="form-control-file" id="photo" placeholder="Escolha uma imagem" required />
        </div>
        <div class="form-group">
            <label for="photo2">Segunda Imagem</label>
            <input type="file" name="photo2" class="form-control-file" id="photo2" placeholder="Escolha uma imagem" required />
        </div>
        <div class="form-group">
            <label for="photo3">Segunda Imagem</label>
            <input type="file" name="photo3" class="form-control-file" id="photo3" placeholder="Escolha uma imagem" required />
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-dark btn-block"> Criar Postagem  </button>
        </div> <!-- form-group// -->
    </form>

</div>
{% endblock %}

enquete/templates/user/dashboard.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

{{message}}


<main role="main" style="background-color: black;">

    <section class="jumbotron text-center" 
        style="background-color: black;  margin-bottom: 4em; ">
      <div class="container" style="height:1.4em; background-color: black;">
        <h3 class="jumbotron-heading">Seus Jogos</h3>
        <p class=" text-muted">Avalie e Seja Avaliado Por uma comunidade de Usuários e Designers!</p>
        <p>
          <a href="{% url 'review:form_post' custom.id %}" class="btn btn-primary my-2">Cadastrar Post do Seu Game</a>
        </p>
      </div>
    </section>

    <div class="album py-5" style="background-color: black;">
      <div class="container">

        <div class="row">
          {% for post in custom.post_set.all %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">

                <div id="carouselExampleIndicators{{forloop.counter}}" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    {% for img in post.postImagens.all %}
                      <li data-target="#carouselExampleIndicators{{forloop.counter}}" 
                      data-slide-to="{{forloop.counter}}" class="{% if forloop.counter == 1 %}active{% endif %}"></li>
                      
                    {% endfor %}
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img class="d-block w-100" src="{{ post.postImagens.first.image.url }}" alt="First slide">
                    </div>
                    {% for img in post.postImagens.all %}
                      {% if img == post.postImagens.first %}
                      
                      {% else %}
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{{ img.image.url }}" alt="First slide">
                      </div>
                      {% endif %}

                    {% endfor %}
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators{{forloop.counter}}" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators{{forloop.counter}}" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>



                
                <div class="card-body">

                  <h5 class="card-title" style="color:black;" >{{post.titulo}}</h5>
                  <h6 class="card-subtitle mb-2 text-muted">Desenvolvedor: {{post.user.username}}</h6>
                  <p class="card-text">{{post.descricao}}</p>

                  <div class="d-flex justify-content-between align-items-center">
                      <div class="d-flex justify-content-between align-items-center">
                        <span class="rating">
                          {% for i in 'cinco' %}
                            {% if forloop.counter <= post.mediaEstrelas %}
                              <i class="uk-icon-star" style="color: rgb(226, 226, 3);"></i>
                            {% else %}
                              <i class="uk-icon-star"></i>
                            {% endif %}
                          {% endfor %}
                        </span>
                      </div>
                    
                      <p>
                        <a href="{% url 'review:detalhes' post.id %}" class="btn btn-primary my-2">Detalhes</a>
                      </p>
                                      
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          


      </div>
    </div>

  </main>

{% endblock %}

enquete/templates/user/login.html
{% extends 'base.html' %}

{% block content %}

{{error}}
<div class="container w-50" align="center" >
<div class="login-form" >
    <form action="{% url 'review:realizarlogin' %}" method="POST">
        {% csrf_token %}
        <h2 class="text-center">Entrar</h2>
        <div class="form-group">
        	<div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        <span class="fa fa-user"></span>
                    </span>
                </div>
                <input type="text" class="form-control" name="username" id="username" placeholder="Username" required="required">
            </div>
        </div>
		<div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">
                        <i class="fa fa-lock"></i>
                    </span>
                </div>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password" required="required">
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-dark login-btn btn-block">Entrar</button>
        </div>
        <!--
        <div class="clearfix">
            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>
            <a href="#" class="float-right">Forgot Password?</a>
        </div>
        -->
    </form>
</div>

</div>
{% endblock %}

enquete/templates/user/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container w-50" align="center" >
    <form action="{% url 'review:cadastro' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>Usuario </label>
              <input type="text" name="username" id="username" class="form-control" placeholder="">
        </div> <!-- form-group end.// -->
        <div class="form-row">
            <div class="col form-group">
                <label>Nome </label>
                  <input type="text" name="first_name" id="first_name" class="form-control" placeholder="">
            </div> <!-- form-group end.// -->
            <div class="col form-group">
                <label>Sobrenome</label>
                  <input type="text" name="last_name" id="last_name" class="form-control" placeholder=" ">
            </div> <!-- form-group end.// -->
        </div> <!-- form-row end.// -->
        <div class="form-group">
            <label>Email</label>
            <input type="email" name="email" id="email" class="form-control" placeholder="">
        </div> <!-- form-group end.// -->
        <div class="form-group">
            <label>Senha</label>
            <input class="form-control" type="password" name="password" id="password">
        </div> <!-- form-group end.// -->

        <div class="form-group">
            <label for="photo">Escolha uma Imagem:</label>
            <input type="file" name="photo" class="form-control-file" id="photo" placeholder="Escolha uma imagem" required />
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-dark btn-block"> Cadastrar  </button>
        </div> <!-- form-group// -->
    </form>

</div>
{% endblock %}